repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.4

      # yamllint disable-line rule:braces
      hooks: [{ id: ruff }, { id: ruff-format }]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-added-large-files
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1

      # yamllint disable-line rule:braces
      hooks: [{ id: yamllint }]
