[tool.black]
line-length = 100
target-version = ["py312"]
exclude = '''
(
  ^data/|
  ^caddy_data/|
  ^caddy_config/|
  ^grafana_data/|
  ^prom_data/|
  ^node_modules/|
  ^\.venv/|
  ^dist/|^build/
)
'''

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = [
  "data",
  "caddy_data",
  "caddy_config",
  "grafana_data",
  "prom_data",
  "node_modules",
  ".venv",
  "dist",
  "build",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM"]
ignore = []

[tool.ruff.format]
quote-style = "double"
