name: auto-tag-and-release

on:
  push:
    branches: [main]

permissions:
  contents: write   # required to create tags & releases

jobs:
  tag:
    name: Bump tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Bump the version automatically (default = patch). Options: major | minor | patch | none
      - name: Create new tag
        id: tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          PRERELEASE: false
          DRY_RUN: false

  build:
    name: Build artifacts
    needs: tag
    if: ${{ needs.tag.outputs.new_tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Build sdist & wheel
        run: |
          python -m pip install -U pip build
          python -m build
          ls -l dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*

  release:
    name: Create GitHub Release
    needs: [tag, build]
    if: ${{ needs.tag.outputs.new_tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag.outputs.new_tag }}
          generate_release_notes: true
          files: |
            dist/*
