name: CI
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install black ruff
      - run: black --check .
      - run: ruff check .

  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: velu-app
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build on PRs only (no push)
      - name: Build (no push)
        if: github.event_name == 'pull_request'
        run: |
          owner_lc="${GITHUB_REPOSITORY_OWNER,,}"
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            --tag "ghcr.io/${owner_lc}/${IMAGE_NAME}:sha-${GITHUB_SHA}" \
            --load .

      # Build & push on main
      - name: Build & Push (main → :latest and :sha)
        if: github.ref == 'refs/heads/main'
        run: |
          owner_lc="${GITHUB_REPOSITORY_OWNER,,}"
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            -t "ghcr.io/${owner_lc}/${IMAGE_NAME}:latest" \
            -t "ghcr.io/${owner_lc}/${IMAGE_NAME}:sha-${GITHUB_SHA}" \
            --push .

      # Build & push on tags vX.Y.Z
      - name: Build & Push (tag → :vX.Y.Z)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          owner_lc="${GITHUB_REPOSITORY_OWNER,,}"
          tag="${GITHUB_REF#refs/tags/}"
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            -t "ghcr.io/${owner_lc}/${IMAGE_NAME}:${tag}" \
            --push .
