name: ci

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "feat/**" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dev deps
        run: |
          python -m pip install -U pip
          pip install black ruff pytest requests

      - name: Lint (black --check)
        run: black --check .

      - name: Lint (ruff)
        run: ruff check .

      # light unit tests (no docker-in-docker)
      - name: Run unit tests
        run: pytest -q
