name: CI
"on":
    push:
    pull_request:
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Upgrade pip
              run: python -m pip install --upgrade pip

            - name: Install deps
              run: |
                  pip install -r requirements.txt
                  pip install pre-commit pip-audit cyclonedx-bom

            - name: Lint (ruff)
              run: |
                  ruff check .
                  ruff format .
                  git diff --exit-code

            - name: Run tests (pytest)
              run: pytest -q

            - name: Security audit (pip-audit)
              run: pip-audit -r requirements.txt

            # Use module form to avoid PATH issues with the CLI shim
            - name: SBOM (CycloneDX)
              run: python -m cyclonedx_bom -r -o sbom.xml

            - name: Upload SBOM artifact
              uses: actions/upload-artifact@v4
              with:
                  name: sbom.xml
                  path: sbom.xml
                  if-no-files-found: error
