name: CI

on:
  push:
    branches: [ main, dev ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, dev ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install black ruff
      - run: black --check .
      - run: ruff check .

  docker-build:
    runs-on: ubuntu-latest
    env:
      IMAGE_OWNER: ${{ github.repository_owner }}   # we'll lowercase in bash
      IMAGE_NAME: velu-app
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build (no push)
        run: |
          owner_lc="${IMAGE_OWNER,,}"  # bash lowercase; avoids toLower() schema fuss
          docker buildx build \
            --tag "ghcr.io/${owner_lc}/${IMAGE_NAME}:sha-${GITHUB_SHA}" \
            --provenance=false \
            --load \
            .
