name: ci

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src:data/src
      API_KEYS: ""
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Git identity (for agent commits in tests)
        run: |
          git config --global user.email "ci@velu.local"
          git config --global user.name  "Velu CI"

      - name: Install deps
        run: |
          python -m pip install -U pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          [ -f tests/requirements.txt ] && pip install -r tests/requirements.txt || true
          pip install fastapi uvicorn pytest ruff black requests

      - name: Lint
        run: |
          ruff check .
          black --check . || true

      - name: Run tests (server + worker; no auth in CI)
        run: |
          set -e
          mkdir -p .run
          export TASK_DB="$PWD/.run/jobs.db"
          export PYTHONPATH="src:data/src"

          # start API server WITHOUT auth
          nohup env TASK_DB="$TASK_DB" PYTHONPATH="src" \
            uvicorn services.app_server.main:create_app --factory --host 127.0.0.1 --port 8010 &

          # start worker (pipeline on), also WITHOUT auth
          nohup env TASK_DB="$TASK_DB" WORKER_ENABLE_PIPELINE=1 WORKER_MAX_JOBS=0 PYTHONPATH="$PYTHONPATH" \
            python -m services.worker.main &

          sleep 3
          pytest -q
