name: ci

on:
  pull_request:
    branches: [ "**" ]        # run on any PR (agent-created too)
  push:
    branches: [ "**" ]        # run on any branch push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src:data/src
      API_KEYS: ""
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          [ -f tests/requirements.txt ] && pip install -r tests/requirements.txt || true
          pip install fastapi uvicorn pytest ruff black requests

      - name: Lint
        run: |
          ruff check .
          black --check . || true

      - name: Run tests (with live server)
        run: |
          nohup uvicorn services.app_server.main:create_app --factory --host 127.0.0.1 --port 8010 &
          sleep 3
          pytest -q
