name: Docker Publish

on:
  push:
    branches: [ main ]     # build :main on every push to main
    tags: [ 'v*' ]         # build :vX.Y.Z (and we’ll also mark :latest)

permissions:
  contents: read
  packages: write   # required to push to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate tags for main/tags
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/velu-app
          tags: |
            # Pushes to main => :main
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # Git tags v*  => :vX.Y.Z and :latest
            type=ref,event=tag
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
