name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          if [ -f tests/requirements.txt ]; then
            pip install -r tests/requirements.txt
          else
            echo "No tests/requirements.txt, skipping."
          fi


      - name: Configure git identity for tests
        run: |
          git config --global user.email "ci@velu.local"
          git config --global user.name  "Velu CI"

      - name: Run tests
        run: pytest -q
