name: lint-and-test

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Configure git identity
        run: |
          git config --global user.email "ci@velu.local"
          git config --global user.name  "Velu CI"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
          # ensure core frameworks present
          pip install fastapi uvicorn pytest ruff black requests

      - name: Lint (non-blocking, 2025 syntax)
        run: |
          ruff check .
          black --check . || true

      - name: Run tests (with live server)
        env:
          API_KEYS: ""
          PYTHONPATH: src
        run: |
          nohup uvicorn services.app_server.main:create_app --factory --host 127.0.0.1 --port 8010 &
          sleep 3
          pytest -q
