name: security-scan

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: "pip" }
      - run: |
          python -m pip install -U pip
          pip install bandit
          bandit -r agents orchestrator services -x "*/tests/*" -q

  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: "pip" }
      - run: |
          python -m pip install -U pip
          pip install pip-audit
          pip-audit -r requirements.txt || true  # warn-only for now
